<!DOCTYPE html>
<html>
    <head>
        <title>Gerador de CRUD - VERSÃO <?= $VERSAO;?></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="/css/bootstrap/bootstrap.css"/>
    </head>
    <body>
        <h2>Gerador de CRUD</h2>
        <form class="form-horizontal" role="form" method="post" action="">
            <input type="hidden" name="enviar" value="true" />
            <fieldset>
                <legend>Informações para a documentação</legend>
                <div class="form-group"> 
                    <label class="control-label col-sm-2" for="autor">Autor: </label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" name="autor" value="<?= $CONF->getAutor();?>" />
                    </div>
                </div>
                <div class="form-group"> 
                    <label class="control-label col-sm-2" for="emialAutor">Email do Autor: </label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" name="emailAutor" value="<?= $CONF->getEmailAutor();?>" />
                    </div>
                </div>
            </fieldset>
            <section id="geracaoBanco">
                <fieldset>
                    <legend> Informações básicas</legend>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="gerarBanco"> Gerar Banco:                            </label>
                        <div class="col-sm-8">
                            <input type="checkbox" class="form-control" 
                                   name="gerarBanco" id="gerarBanco" value="true"
                                   <?= $CONF->getGerarBanco(); ?> />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="bd">Nome Banco:</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="bd" name="nomeBanco" placeholder="Nome do Banco de dados" value="<?= $CONF->getBanco(); ?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="gerarBanco"> Modo admin:  </label>
                        <div class="col-sm-8">
                            <input type="checkbox" class="form-control" 
                                   name="modoAdmin" id="modoAdmin" value="true"
                                   <?= $CONF->isAdmin(); ?>/>
                        </div>
                    </div>
                </fieldset>
                <fieldset>
                    <legend> Configurações adicionais <a id="openConf" title="open conf">[+]</a></legend>
                    <div id="conf">
                    <div class="form-group">
                        <label class="campoCurto">
                            Deletar:
                            <input type="checkbox" name="deletar" value="true" <?= $CONF->getDeletar(); ?>/>
                        </label>
                        <label class="campoCurto">
                            URL REWRITE:
                            <input type="checkbox" name="rewrite" value="true" <?= $CONF->getRewrite(); ?>/>
                        </label>
                    </div>
                    <label class="campoCurto">
                        URL Adicional:
                        <input type="text" name="urlAdicional" value="<?= $CONF->getUrlAdicional(); ?>"/>
                    </label>
                    </div>
                </fieldset>
            </section>
            <fieldset id="geracaoDTO">
                <legend> Apenas DTOS das tabelas</legend>
                <div class="form-group">
                    <label class="control-label col-sm-2" for="nomeDao" id="nomeDTO"> 
                        Tabelas </label>
                    <div class="col-sm-8"  >
                        <textarea id="nomeDao" class="form-control" 
                                  placeholder="ex: tabela, public.tabela, public.*, ou deixe em branco para todas" 
                                  name="nomeDao"><?= $nomeDao; ?></textarea>
                    </div>
                </div>

                <div class="form-group" id="campos">
                    <div class="col-sm-8"  >
                        <label  class="control-label col-sm-2" for="campos">Campos:</label>
                        <textarea id="campos" class="form-control" name="campos"><?= $campos; ?></textarea>

                    </div>
                </div>
            </fieldset>
            <fieldset>

                <div class="form-group">

                    <div class="col-sm-offset-2 col-sm-1">
                        <button type="reset" class="btn btn-default btn-danger">Reset</button>
                    </div>

                    <div class="col-sm-2">
                        <button type="submit" class="btn btn-default btn-success">Gerar</button>
                    </div>
                </div>
            </fieldset>
        </form>
        <div id="resultado" class="col-sm-offset-2 col-sm-8">
            <pre><?= $RESULTADO;?></pre>
        </div>

        <script src="/js/dist/jquery/jquery.js"></script>
        <script><?= $SCRIPT ?></script>
    </body>
</html>
