#!/bin/bash

if [ -z "$1"]; #checa se foi passado 1 argumentp
  then
  
  PROJETO=$( dialog  --backtitle '== Escolha do projeto ==' --stdout --inputbox 'Digite o diretorio raiz do projeto' 0 200 "/var/www/"  )

else
    PROJETO=$1
fi



cd $PROJETO/core/view/core_client
grunt w
