#!/bin/bash

if [ -z "$1" -a -z "$2" ] #checa se foi passado 2 argumentos
  then
  dialog                                          \
   --title 'Esse programa necessita de 2 argumentos'                              \
   --yesno '\nSe você confirmar a saida o conteúdo da pasta será apagado\n\n'    \
   0 0
    exit;
else
    NOVODIR=$1
    PROJETO=$2
fi


#gera projeto netbeans
    mkdir $NOVODIR/nbproject
    echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<project xmlns=\"http://www.netbeans.org/ns/project/1\">
    <type>org.netbeans.modules.php.project</type>
    <configuration>
        <data xmlns=\"http://www.netbeans.org/ns/php-project/1\">
            <name>$PROJETO</name>
        </data>
    </configuration>
</project>" > $NOVODIR/nbproject/project.xml


   echo "auxiliary.org-netbeans-modules-php-smarty.smarty-framework=true
include.path=\${php.global.include.path}
php.version=PHP_54
source.encoding=UTF-8
src.dir=.
tags.asp=false
tags.short=false
web.root=." > $NOVODIR/nbproject/project.properties